# Generated by Django 5.0 on 2023-12-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0002_sport_type_sportsmen_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='win_coynty',
            field=models.TextField(default='Победила дружба'),
        ),
    ]
