# Generated by Django 5.0 on 2023-12-29 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, unique=True, verbose_name='логин')),
                ('passw', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], 
                                           verbose_name='пароль')),
                ('available', models.BooleanField(default=True, verbose_name='ждет выдачи')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='контактный телефон')),
                ('org', models.CharField(max_length=255, verbose_name='название организации')),
                ('region', models.CharField(default='Курск', max_length=255, verbose_name='область (город)')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
                'ordering': ['-updated_at'],
            },
        ),
    ]
