# Generated by Django 5.0 on 2024-01-01 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, unique=True, verbose_name='логин')),
                ('passw', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='пароль')),
                ('busy', models.BooleanField(default=False, null=True, verbose_name='выдана')),
                ('fio', models.CharField(max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='контактный телефон')),
                ('org', models.CharField(max_length=255, null=True, verbose_name='название организации')),
                ('region', models.CharField(default='Курск', max_length=255, null=True, verbose_name='область (город)')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Учетная запись',
                'verbose_name_plural': 'Учетные записи',
                'db_table': 'Account',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Test',
            },
        ),
    ]
