# Generated by Django 5.0 on 2023-12-29 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fio',
            field=models.CharField(max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='account',
            name='org',
            field=models.CharField(max_length=255, null=True, verbose_name='название организации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='passw',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='контактный телефон'),
        ),
        migrations.AlterField(
            model_name='account',
            name='region',
            field=models.CharField(default='Курск', max_length=255, null=True, verbose_name='область (город)'),
        ),
    ]
