# Generated by Django 5.0 on 2023-12-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_alter_account_fio_alter_account_org_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='available',
        ),
        migrations.AddField(
            model_name='account',
            name='busy',
            field=models.BooleanField(default=False, null=True, verbose_name='выдана'),
        ),
    ]
