# Generated by Django 5.0.1 on 2024-03-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_news_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='adress',
            field=models.CharField(default=1, max_length=100, verbose_name='Адес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='phone_number',
            field=models.CharField(default=1, max_length=13, verbose_name=' Номер телефон'),
            preserve_default=False,
        ),
    ]
