# Generated by Django 5.0.3 on 2024-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_news_full_text_alter_news_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='address',
            field=models.CharField(default=1, max_length=60, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='phone_number',
            field=models.CharField(default=1, max_length=12, verbose_name='номер телефона пользователя'),
            preserve_default=False,
        ),
    ]
