# Generated by Django 5.0.3 on 2024-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_news_address_news_last_name_news_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='is_public',
            field=models.BooleanField(default='false', verbose_name='для открытой печати'),
        ),
    ]
