# Generated by Django 5.0.3 on 2024-03-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0004_alter_news_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='news',
            name='is_public',
            field=models.BooleanField(default='False', verbose_name='для открытой печати'),
        ),
    ]
