# Generated by Django 5.0.3 on 2024-04-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0005_remove_news_phone_number_alter_news_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_url',
            field=models.CharField(max_length=300, null=True, verbose_name='ссылка на картинку'),
        ),
    ]
