# Generated by Django 5.0 on 2023-12-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.game')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.person')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.sport')),
            ],
        ),
    ]
