# Generated by Django 5.0.3 on 2024-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='about',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
