# Generated by Django 5.0.3 on 2024-03-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planets', '0002_planets_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='pic',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
