# Generated by Django 5.0.3 on 2024-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planets', '0003_planets_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='planets',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
