# Generated by Django 5.0.1 on 2024-03-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_news_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='adress',
            field=models.CharField(default=11111, max_length=100, verbose_name='адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='last_name',
            field=models.CharField(default=1, max_length=37, verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='phone_number',
            field=models.CharField(default=1, max_length=12, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
