# Generated by Django 5.0 on 2023-12-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Adress', models.CharField(max_length=255)),
                ('Telephone_number', models.FloatField()),
                ('Email', models.CharField(max_length=255)),
            ],
        ),
    ]
