# Generated by Django 5.0 on 2023-12-16 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=255)),
                ('Product_price', models.FloatField()),
                ('Product_availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_date', models.DateField()),
                ('Order_sum', models.FloatField()),
                ('Number_of_products', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Zakaz',
            new_name='Client',
        ),
        migrations.CreateModel(
            name='OnlineOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Client_Name', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.client')),
                ('Product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.goods')),
                ('Data_Time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.orders')),
            ],
        ),
    ]
