# Generated by Django 5.0 on 2023-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0002_goods_orders_rename_zakaz_client_onlineorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Gender',
            field=models.CharField(default='Укажите Ваш пол', max_length=255),
        ),
    ]
