# Generated by Django 5.0.1 on 2024-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0002_news_full_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='address',
            field=models.CharField(default=1, max_length=60, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='phon_number',
            field=models.BooleanField(default=1, max_length=12, verbose_name='номер телефона пользователя'),
            preserve_default=False,
        ),
    ]
