# Generated by Django 5.0.1 on 2024-03-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my', '0003_news_address_news_last_name_news_phon_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='phon_number',
            field=models.CharField(max_length=12, verbose_name='номер телефона пользователя'),
        ),
    ]
