# Generated by Django 5.0 on 2023-12-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Breed', models.CharField(max_length=255)),
                ('Age', models.FloatField()),
                ('Gender', models.CharField(max_length=255)),
                ('Owner', models.CharField(max_length=255)),
            ],
        ),
    ]
