# Generated by Django 5.0 on 2023-12-16 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Specialization', models.CharField(max_length=255)),
                ('Working_hours', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Telephone_number', models.FloatField()),
                ('Address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Session_Time', models.DateTimeField()),
                ('Date_Time', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.doctor')),
                ('Pacient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pr8.pacient')),
            ],
        ),
    ]
