# Generated by Django 5.0 on 2023-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pr8', '0002_doctor_owner_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='Gender',
            field=models.CharField(default='Введите Ваш пол', max_length=255),
        ),
    ]
